### ISSUE TITLE
Avoid NoSuchFileException by building cache.ser if it doesn't exist

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#547] opened 2018-06-27 21:24 UTC
https://sentry.io/opendatakit/briefcase/issues/591991089/

```
UncheckedIOException: java.nio.file.NoSuchFileException: <root>/ODK Briefcase Storage/cache.ser
    at org.opendatakit.briefcase.reused.UncheckedFiles.createFile(UncheckedFiles.java:133)
    at org.opendatakit.briefcase.util.FormCache.setLocation(FormCache.java:80)
    at org.opendatakit.briefcase.util.FormCache.from(FormCache.java:54)
    at org.opendatakit.briefcase.operations.ImportFromODK.importODK(ImportFromODK.java:52)
    at org.opendatakit.briefcase.operations.ImportFromODK.lambda$static$1(ImportFromODK.java:42)
...
(9 additional frame(s) were not displayed)

NoSuchFileException: <root>/ODK Briefcase Storage/cache.ser
    at org.opendatakit.briefcase.reused.UncheckedFiles.createFile(UncheckedFiles.java:131)
...
(15 additional frame(s) were not displayed)

Error
```

**Comment by ggalmazor** [comment] 2018-06-27 21:32
I can only reproduce this one by remove (or moving) the whole storage dir.

The error is misleading because what's really happening is that the user has set a storage directory that doesn't exist.

We could add to the CLI the same control we've added to the main window to check for this. In this case, I'd exit with an error status and some message alerting of the fact that the storage dir doesn't exist.

**Comment by lognaturel** [comment] 2018-06-27 22:54
Sigh. I always forget that the storage directory should actually be set to the directory that contains the storage directory.

If I delete just the `ser` file, I get
```
java.io.EOFException: null
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2353)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2822)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:301)
	at org.opendatakit.briefcase.util.FormCache.setLocation(FormCache.java:65)
	at org.opendatakit.briefcase.util.FormCache.from(FormCache.java:54)
	at org.opendatakit.briefcase.operations.Export.export(Export.java:71)
	at org.opendatakit.briefcase.operations.Export.lambda$static$2(Export.java:54)
	at org.opendatakit.common.cli.Cli.lambda$run$4(Cli.java:126)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.opendatakit.common.cli.Cli.run(Cli.java:123)
	at org.opendatakit.briefcase.Launcher.main(Launcher.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
```

**Comment by ggalmazor** [comment] 2018-06-28 08:01
I can get an EOF exception by truncating the size of the cache file, which could happen naturally with a corrupt cache file or if somehow the process of writing it gets stopped midway. 

In any case, Briefcase recovers from this situation and you only see a warning on the logs. I'll add a special case for EOF exceptions to _not_ log it as I don't think it's really an actionable report. We can discuss this on the PR too.

**Comment by ggalmazor** [comment] 2018-06-28 08:22
Sentry issue: [BRIEFCASE-78](https://sentry.io/opendatakit/briefcase/issues/573988493/)

**Comment by ggalmazor** [comment] 2018-06-28 08:23
Sentry issue: [BRIEFCASE-AT](https://sentry.io/opendatakit/briefcase/issues/591965526/)

**Comment by ggalmazor** [comment] 2018-06-28 08:50
Sentry issue: [BRIEFCASE-AV](https://sentry.io/opendatakit/briefcase/issues/591965563/)

**Comment by ggalmazor** [comment] 2018-06-28 09:35
Sentry issue: [BRIEFCASE-77](https://sentry.io/opendatakit/briefcase/issues/573987702/)

**Comment by ggalmazor** [comment] 2018-06-28 09:37
Sentry issue: [BRIEFCASE-7Y](https://sentry.io/opendatakit/briefcase/issues/575266465/)

**Comment by ggalmazor** [comment] 2018-06-28 17:51
Since we've approved #554, I guess I can close this one...

**Closed** 2018-06-28 18:44 UTC
