### ISSUE TITLE
Only duplicate media on export when there are truly unique

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#77] opened 2017-03-22 01:03 UTC
Collect uses timestamps to name files. On a very large campaign, two devices can take images at the same time, upload them both to Aggregate, then download them to Briefcase. When those images are exported, what happens?

**Comment by rclakmal** [comment] 2017-03-25 01:45
Tested on OS X 10.12 with `Birds` form

There were two images with the same timestamp in two difference instance folders.
![snip20170325_1](https://cloud.githubusercontent.com/assets/794011/24318395/e9d057cc-1104-11e7-9507-dd13ab2dc22c.png)

After exporting, in the media folder, one was renamed with the `suffix -2`

![snip20170325_2](https://cloud.githubusercontent.com/assets/794011/24318410/166fc394-1105-11e7-82f7-89ad34475770.png)

**Comment by shivam-tripathi** [comment] 2017-03-25 17:33
@yanokwa Confirmed the same thing as @rclakmal 
![selection_016](https://cloud.githubusercontent.com/assets/9463078/24324588/1933d8d6-11af-11e7-92b9-da18a61383a8.png)
![selection_017](https://cloud.githubusercontent.com/assets/9463078/24324589/20846b50-11af-11e7-8353-5323582fbc91.png)

**Comment by shivam-tripathi** [comment] 2017-03-25 17:44
But noticed something weird : 
![selection_018](https://cloud.githubusercontent.com/assets/9463078/24324666/99f622ac-11b0-11e7-8be3-e0d7cfcac91b.png)
![selection_019](https://cloud.githubusercontent.com/assets/9463078/24324668/a0c2a718-11b0-11e7-935e-589924a746fc.png)

It appears that when encountering two separate instance media with same time stamp, it creates a duplicate of the one it encountered first.

**Comment by shivam-tripathi** [comment] 2017-03-25 19:18
Looked at the code. I was mistaken. Making changes to the instances folder makes no difference.
![selection_020](https://cloud.githubusercontent.com/assets/9463078/24325388/d5faf05e-11bd-11e7-8017-e23ecfd64c56.png)

**Comment by icemc** [comment] 2017-03-26 13:29
I confirm what @shivam-tripathi said earlier. When the code encounters files with the same time stamp it solves the problem by adding an incremental suffix.

**Comment by yanokwa** [comment] 2017-04-05 17:22
Thanks so much for the confirmation, gentlemen! I'm closing this issue because this is exactly the behavior we want.

**Comment by yanokwa** [comment] 2017-04-06 18:53
Actually. Instead of adding image-2.jpg, I wonder if we can check the MD5 hash and only append a number if those files are actually different. What do you think @shivam-tripathi @icemc @rclakmal?

**Comment by rclakmal** [comment] 2017-04-06 19:19
@yanokwa We can store MD5 hashes and file paths in a HashTable. MD5 hash would be the key. This will allow us to skip the duplicates. As far as I know, there is a theoretical possibility, however small, that two different files could return same hash. I think we can ignore this for practocal purposes?

Wouldn't you think we should provide this as an option? This introduce extra overhead to the export process and in a big form result set delay could be noticeble.

**Comment by icemc** [comment] 2017-04-06 22:21
@yanokwa  following what @rclakmal  said and MD% has will solve the problem (in most cases) but will decease the performance during export of forms with a large amount of instances. It is left for the community to decide if this extra cost is necessary.

**Comment by yanokwa** [comment] 2017-04-06 23:15
I'd rather we decide what is best than add options to the app. I think this should be pretty fast because you'd only be doing the MD5 check when you have a matching filename, no?

**Comment by shivam-tripathi** [comment] 2017-04-07 14:01
With everyone's permission, I would be glad to look into this.

**Comment by rclakmal** [comment] 2017-04-07 14:34
@shivam-tripathi Sure go ahead :-) I did a basic comparison already on MD5 and SHA1.  MD5 was faster and looks suitable for our use case. Let me know if any assistance is needed from my side.

**Comment by icemc** [comment] 2017-04-07 14:40
@shivam-tripathi  sure u can look into it. I don't think someone is currently working on it. Did a quick look and seems like the issue comes from the file ConvertToCSV.java in the method emitSubmissionCsv in case org.javarosa.core.model.Constants.DATATYPE_BINARY: correct me if I'm wrong. Hope I helped

**Comment by joeflack4** [comment] 2017-04-10 14:40
Thanks for your efforts with this. Some of our partners have very limited connections, so the duplicate issues can be a huge issue, particularly with our fork of collect which uses form linking, as some images are shared between our household and individual questionnaires.

**Comment by shivam-tripathi** [comment] 2017-04-10 16:00
@joeflack4 Hi!
Presently we are trying to remove redundancy when you export the data collected using Briefcase _after_ pulling it from the server. This is essentially an offline process. 
However, while pulling the data off the server - this remains an issue. I hope some solution surfaces in future. If I am correct, it needs to be done at Aggregate or even better at Collect level - as in Briefcase we cannot determine whether or not the media file is duplicate before the fetch.

**Closed** 2017-04-30 15:35 UTC
Labels: contributor friendly, enhancement, in progress
