### ISSUE TITLE
CSV filename is not safe on all file systems

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#230] opened 2017-10-25 17:58 UTC
Currently `ExportToCsv.safeFilename` removes punctuation and spaces, but it allows Unicode and characters that might cause problems on other file systems. I propose only allowing only ASCII characters, space, hyphen, and underscore (similar to https://github.com/opendatakit/briefcase/pull/224). 

So a CSV called "Båé Førm.csv" would now be "B Frm.csv".

**Comment by dcbriccetti** [comment] 2017-10-25 18:12
Or, to avoid name collisions, encode it somehow, such as URL encoding:
B%C3%A5%C3%A9%20F%C3%B8rm.csv

**Comment by yanokwa** [comment] 2017-10-25 18:18
URL encoding isn't very humane to me and thus feels worse.

**Comment by dcbriccetti** [comment] 2017-10-25 18:24
It could also be that Båé Førm is perfectly valid as a path and filename in Windows, GNU/Linux, MacOS (or whatever they call it now) and Android. Maybe @nribeka can research.

**Comment by nribeka** [comment] 2017-10-31 15:02
I tried that Båé Førm and it worked fine on both mac and windows. I couldn't find any other limitation other than the one I found about dot at the end:

https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx

**Comment by ggalmazor** [comment] 2018-02-19 15:29
Do we have a specific example of an unsafe name that we use to create a test and work on this one? If not, I'd suggest closing this issue. We can reopen if some unsafe name comes by.

**Comment by ggalmazor** [comment] 2018-02-19 15:29
@opendatakit-bot label "needs reproduction"

**Comment by yanokwa** [comment] 2018-08-31 21:02
I'm hesitating at closing this because it points to a higher level issue of how what we allow as file names. So for example in #224 (https://github.com/opendatakit/briefcase/pull/224/commits/1ecaa5ff476a5974538d300e19d1526e048abf18#diff-cf12604ffa6f5eb5f610a0f9121717bcR39) we remove a bunch of bad characters in the title, but we don't do the same when we export to CSV. Seems like we should be consistent.

**Comment by ggalmazor** [comment] 2018-09-03 09:31
I think this is no longer true. We're using `StringUtils.stripIllegalChars()` on the export filenames since our last changes to the export process...

**Comment by ggalmazor** [comment] 2018-09-03 09:33
Now I'm wondering if I'm missing any other file output that Briefcase might produce...

**Comment by ggalmazor** [comment] 2018-09-05 09:43
I've checked this and there were two places that didn't use the `stripIllegalChars` method. I've created a PR to fix that.

**Closed** 2018-09-07 16:17 UTC
