### ISSUE TITLE
Unable to run briefcase on java 9 and 10 without clearing prefs.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#498] opened 2018-06-06 13:34 UTC
#### Software versions 
Briefcase v1.10.x, Java v1.9, v1.10, operating system all when using sdkman

#### Problem description
After using briefcase on java 8, I changed java version to 9/10 using sdkman tool and try to run it - running failed.
When I cleared prefs I was able to run briefcase on both java 9 and 10

When I uninstalled manually java 8 on windows and install java 9/10 I was able to run briefcase.

#### Expected behavior
I think that most user will update java version manually but a bad news is that used to work on briefcase 10 release so it can be some kind of regression. @lognaturel @yanokwa @ggalmazor 

#### Other information 
Content of cmd response:
```
2018-06-06 15:22:39,602 [main] ERROR o.o.a.p.BaseFormParserForJavaRosa - Failed to launch GUI
java.lang.IllegalStateException: Duplicate key build_Untitled-Form_1509107185 (attempted merging values org.opendatakit.briefcase.model.FormStatus@47874b25 and org.opendatakit.briefcase.model.FormStatus@33617539)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:131)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1494)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:511)
	at org.opendatakit.briefcase.push.PushForms.rebuildIndex(PushForms.java:87)
	at org.opendatakit.briefcase.push.PushForms.<init>(PushForms.java:35)
	at org.opendatakit.briefcase.ui.push.PushPanel.from(PushPanel.java:96)
	at org.opendatakit.briefcase.ui.MainBriefcaseWindow.<init>(MainBriefcaseWindow.java:117)
	at org.opendatakit.briefcase.ui.MainBriefcaseWindow.launchGUI(MainBriefcaseWindow.java:79)
	at org.opendatakit.briefcase.Launcher.lambda$main$1(Launcher.java:75)
	at org.opendatakit.common.cli.Cli.lambda$run$5(Cli.java:132)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.opendatakit.common.cli.Cli.run(Cli.java:132)
	at org.opendatakit.briefcase.Launcher.main(Launcher.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Failed to launch Briefcase GUI
2018-06-06 15:22:39,617 [googleanalyticsjava-thread-1] WARN  c.b.g.h.ApacheHttpClientImpl - Exception while sending the Google Analytics tracker request com.brsanthu.googleanalytics.httpclient.HttpRequest@6c829953
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1969)
	at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:345)
	at java.base/sun.security.ssl.Handshaker.fatalSE(Handshaker.java:339)
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1968)
	at java.base/sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1777)
	at java.base/sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:264)
	at java.base/sun.security.ssl.Handshaker.processLoop(Handshaker.java:1092)
	at java.base/sun.security.ssl.Handshaker.processRecord(Handshaker.java:1026)
	at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1137)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.brsanthu.googleanalytics.httpclient.ApacheHttpClientImpl.execute(ApacheHttpClientImpl.java:86)
	at com.brsanthu.googleanalytics.httpclient.ApacheHttpClientImpl.post(ApacheHttpClientImpl.java:102)
	at com.brsanthu.googleanalytics.internal.GoogleAnalyticsImpl.postSingle(GoogleAnalyticsImpl.java:165)
	at com.brsanthu.googleanalytics.internal.GoogleAnalyticsImpl.post(GoogleAnalyticsImpl.java:105)
	at com.brsanthu.googleanalytics.internal.GoogleAnalyticsImpl.lambda$postAsync$0(GoogleAnalyticsImpl.java:91)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:343)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:226)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:133)
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1947)
	... 31 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
	... 37 common frames omitted
2018-06-06 15:22:39,618 [googleanalyticsjava-thread-1] WARN  c.b.g.internal.GoogleAnalyticsImpl - Exception while sending the Google Analytics tracker request Request [parms={APPLICATION_NAME=ODK Briefcase, HIT_TYPE=screenview, USER_LANGUAGE=en-US, SESSION_CONTROL=start, CLIENT_ID=9a65f166-9786-4430-9bcf-a77c2696bc69, DOCUMENT_ENCODING=UTF-8, USER_ID=cff2b8f2-67df-4397-8f6f-4b2c2176b038, SCREEN_RESOLUTION=1920x1080, VIEWPORT_SIZE=0x0, ANONYMIZE_IP=true, DATA_SOURCE=app, SCREEN_NAME=Briefcase, PROTOCOL_VERSION=1, APPLICATION_VERSION=v1.10.1-151-gf61342b-dirty, USER_AGENT=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36, TRACKING_ID=UA-91951913-3}, customDimensions={}, customMetrics={}]
java.lang.NullPointerException: null
	at com.brsanthu.googleanalytics.httpclient.ApacheHttpClientImpl.post(ApacheHttpClientImpl.java:113)
	at com.brsanthu.googleanalytics.internal.GoogleAnalyticsImpl.postSingle(GoogleAnalyticsImpl.java:165)
	at com.brsanthu.googleanalytics.internal.GoogleAnalyticsImpl.post(GoogleAnalyticsImpl.java:105)
	at com.brsanthu.googleanalytics.internal.GoogleAnalyticsImpl.lambda$postAsync$0(GoogleAnalyticsImpl.java:91)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by ggalmazor** [comment] 2018-06-06 18:04
@kkrawczyk123, sorry, I can't reproduce. Also, the error trace you've copied points to corruption in your storage directory... Could you try to reproduce from a clean state?

**Comment by kkrawczyk123** [comment] 2018-06-07 08:39
I deleted old storage directory, clear prefs, set new storage directory, briefcase run but I am unable to log in to aggregate's server on Ubuntu and MacOS. Storage directory is empty so it can't be about some wrong form included there. I can see error "javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target." 

I am able to run and connect on Briefcase 1.10.1 - last release version.

**Comment by ggalmazor** [comment] 2018-06-07 11:06
Hi, @kkrawczyk123! Now the error `javax.net.ssl.SSLHandshakeException` is pointing to a networking error... I think AppEngine is giving us a hard time these days. Could you try with my server at https://gigiaggregate.appspot.com or maybe deploy a local server using the VM?

**Comment by kkrawczyk123** [comment] 2018-06-07 13:45
I was able to connect to local aggregate's instance on both systems but still had to clear prefs before running briefcse. After that I was able to use briefcase on both java's 9 and 10.

I am still able to reproduce issue when try to run and connect to gae aggregate's instance.

**Comment by ggalmazor** [comment] 2018-06-07 14:32
I think there's something wrong with those gae instances... do you still think it's a Briefcase issue? 

If not, we can close this one. We can always reopen it if we get new findings...

**Comment by ggalmazor** [comment] 2018-06-07 18:32
@opendatakit-bot unclaim

**Comment by lognaturel** [comment] 2018-06-07 22:18
Maybe the change in Java version is not actually the source of the problem? Seems https://forum.opendatakit.org/t/odk-briefcase-v1-11-beta/13432/8 might be the same.

**Comment by kkrawczyk123** [comment] 2018-06-08 05:29
@ggalmazor You might be right that it could have been an aggregate gae issue, as in the last release I used tomcat instance. I have to investigate deeper after resurrecting my tomcat-aggregate as It's still gone after my computer crashed. And then report an issue to aggregate if needed.

**Comment by ggalmazor** [comment] 2018-06-11 07:02
> Maybe the change in Java version is not actually the source of the problem? Seems https://forum.opendatakit.org/t/odk-briefcase-v1-11-beta/13432/8 might be the same.

I see two different problems reported.
- One it has to do with pulling forms from aggregate
- The other has to do with duplicate forms in the storage directory

It's not very probable that those problems have to do with the Java version used to run Briefcase.

@kkrawczyk123 if you can consistently get the duplicated forms error (The one with the trace `Duplicate key build_Untitled-Form_1509107185`), I think I'd need you to send me your whole storage directory zipped to try to reproduce.

Regarding the other error about pulling from an Aggregate server, I've asked the forum user to do more tests.

**Comment by kkrawczyk123** [comment] 2018-06-12 13:36
Me and @ggalmazor investigated that issue and figured out reproduction steps. It is connected to specific java version.
I created more detailed issue #528  so we can close that one.

**Comment by yanokwa** [comment] 2018-06-12 15:05
Closing in favor of #528

**Closed by yanokwa** 2018-06-12 15:05 UTC
Labels: needs reproduction
