### ISSUE TITLE
Match former expected date format in CLI and include it in help

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#378] opened 2018-02-15 20:21 UTC
#### Software versions 
Briefcase v1.9.0

#### Problem description
Dates used to be provided in yyyy/MM/dd format. Now they are expected in yyyy-MM-dd. Additionally, the format is not specified in the help text and the user sees an unexpected error when the format is wrong.

#### Steps to reproduce the problem
Run an export at the CLI with start and end date specified.

#### Expected behavior
The date format is backwards-compatible and the user is given a nice error message when the date is invalid.

**Comment by mayank8318** [comment] 2018-02-16 17:50
@opendatakit-bot claim

**Comment by mayank8318** [comment] 2018-02-16 17:52
Should I work on this after #356 is merged?

**Comment by yanokwa** [comment] 2018-02-16 18:35
Please go ahead!

**Comment by mayank8318** [comment] 2018-02-21 13:48
@lognaturel @yanokwa @ggalmazor I am getting Invalid date format for this command though - 
`java -jar ODK\ Briefcase\ v1.9.0-102-g4d7e2ff.jar --form_id all-widgets --storage_directory /home/mayank/ --export_directory /home/mayank/ODKExport/ --export_filename abcd.csv -start 2018-01-20`

**Comment by mayank8318** [comment] 2018-02-21 14:01
And dateTimeParseEcxeption for 2018/01/20

**Comment by ggalmazor** [comment] 2018-02-21 19:25
@lognaturel Could it work for you to make both `-` and `/` valid separators? This way we could promote the use of ISO8601 dates that use `-` as the separator for new users and also accept `/` which is what current users expect.

**Comment by mayank8318** [comment] 2018-02-21 19:27
@ggalmazor Yes I can do that by writing a custom parse method using DateTimeFormatter right?

**Comment by ggalmazor** [comment] 2018-02-21 19:28
> custom parse method using DateTimeFormatter right?
I was thinking about just replacing all `/` to `-`. The idea is to normalize the input to ISO8601 format and then parse it. Otherwise, how do you know which formatter to use if we decide to support both ISO6801 format and the one that uses `/` as separator?

**Comment by ggalmazor** [comment] 2018-02-21 19:29
@mayank8318 by the way, I can use `-start 2018-01-20` and it doesn't give me an error...

**Comment by mayank8318** [comment] 2018-02-21 19:30
use indexOf( ) method. Though replacing is better.

**Comment by mayank8318** [comment] 2018-02-21 19:32
Getting this for 2018-01-20 : 
01:00:36.778 [main] ERROR org.opendatakit.aggregate.parser.BaseFormParserForJavaRosa - Invalid date format in export_start_date

**Comment by ggalmazor** [comment] 2018-02-21 19:33
Could you get a full stack trace?

**Comment by mayank8318** [comment] 2018-02-21 19:34
01:03:23.939 [main] DEBUG io.sentry.config.Lookup - Sentry configuration file not found in filesystem or classpath: 'sentry.properties'.
01:03:24.025 [main] DEBUG io.sentry.DefaultSentryClientFactory - Using an HTTPS connection to Sentry.
01:03:24.236 [main] WARN io.sentry.DefaultSentryClientFactory - No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
01:03:24.246 [main] DEBUG io.sentry.DefaultSentryClientFactory - The current environment doesn't provide access to servlets, or provides an unsupported version.
01:03:24.246 [main] DEBUG io.sentry.SentryClient - Adding 'io.sentry.event.helper.ContextBuilderHelper@ea1a8d5' to the list of builder helpers.
01:03:24.248 [main] DEBUG io.sentry.SentryClientFactory - Configuring uncaught exception handler.
01:03:24.249 [main] WARN io.sentry.DefaultSentryClientFactory - No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
01:03:24.337 [main] ERROR org.opendatakit.aggregate.parser.BaseFormParserForJavaRosa - Invalid date format in export_start_date
usage: java -jar briefcase.jar
 -ed,--export_directory </path/to/dir>     Directory to export the CSV and
                                           media files into (relative path
                                           unless it begins with / or C:\)
 -em,--exclude_media_export                Flag to exclude media on export
 -end,--export_end_date <yyyy/MM/dd>       Include submission dates before
                                           (exclusive) this date in export
                                           to CSV
 -f,--export_filename <name.csv>           File name for exported CSV
 -h,--help                                 Print help information (this
                                           screen)
 -id,--form_id <form_id>                   Form ID of form to download and
                                           export
 -oc,--overwrite_csv_export                Flag to overwrite CSV on export
 -od,--odk_directory </path/to/dir>        /odk directory from ODK Collect
                                           (relative path unless it begins
                                           with / or C:\)
 -p,--odk_password <password>              ODK password
 -pf,--pem_file </path/to/file.pem>        PEM private key file (relative
                                           path unless it begins with / or
                                           C:\)
 -sd,--storage_directory </path/to/dir>    Directory to create or find ODK
                                           Briefcase Storage directory
                                           (relative path unless it begins
                                           with / or C:\)
 -start,--export_start_date <yyyy/MM/dd>   Include submission dates after
                                           (inclusive) this date in export
                                           to CSV
 -u,--odk_username <username>              ODK username
 -url,--aggregate_url <url>                ODK Aggregate URL (must start
                                           with http:// or https://)
 -v,--version                              Print version information
01:03:24.340 [Thread-0] DEBUG io.sentry.connection.AsyncConnection - Gracefully shutting

**Comment by ggalmazor** [comment] 2018-02-21 19:35
Try adding `-pa` argument.

**Comment by mayank8318** [comment] 2018-02-21 19:45
@ggalmazor Silly error. Missed the most important `-e` argument. My bad :(

**Comment by ggalmazor** [comment] 2018-02-21 19:47
The problem is that without `-e`, `Launcher` falls back to `MainBriefcaseWindow`, which requires `/` as separator... One day we'll have to unify criteria...

**Comment by mayank8318** [comment] 2018-02-21 19:48
Oh

**Comment by lognaturel** [comment] 2018-02-21 20:04
Accepting both formats sounds perfect to me. That should be the case with and without `-e`.

**Closed** 2018-03-07 22:02 UTC
Labels: bug, contributor friendly, in progress
