### ISSUE TITLE
Fake, empty submissions that prevent export

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#188] opened 2017-09-11 17:04 UTC
User-reported problem at https://forum.opendatakit.org/t/odk-briefcase-export-failed/9727

I'm not totally sure this is a Briefcase problem but it would be good to explore whether there's any way that Briefcase could "generate" a submission. 

Either way, once this has been investigated, it may be worth filing an issue to fail more gracefully in the case of corrupt submissions. Perhaps skip them and report they were skipped?

**Comment by NaderVIP** [comment] 2017-09-21 01:28
you are right
in fact there is no empty submissions we have uuid and even the rest of data empty, briefcase worked OK .
i did it and i export that empty record with uuid without any problems

**Comment by icemc** [comment] 2017-12-01 08:19
Just to throw more light on this. I believe briefcase was interrupting export when it encountered an empty submission but that was fixed a long time ago. So I think the problem is not from briefcase

**Comment by ggalmazor** [comment] 2018-08-31 07:25
I'd close this one if we're not capable of producing a scenario where this is reproduced. We have neither received user reports in the forums since Dec'17.

Also, although I haven't done focused testing of this issue, I've used empty submissions while testing other PRs and it worked.

**Comment by yanokwa** [comment] 2018-08-31 20:58
Agreed with @ggalmazor's logic.

**Closed by yanokwa** 2018-08-31 20:58 UTC
Labels: housekeeping, needs reproduction
