### ISSUE TITLE
Forms are not pulled when `Pull before export` option is selected

### ISSUE THREAD

**Issue by mmarciniak90** [opendatakit/briefcase#512] opened 2018-06-07 10:26 UTC
**EDIT!**
A new bug which can cause this problem:
1. The user opens Briefcase and **does not select** `remember the password`
2. The user connects to aggregate and pulls one form
3. The user goes to `Export` tab and chooses `Export directory`
4. The user exports this one form
5. `Pull before export` checkbox is **ACTIVE**

#### Software versions 
Briefcase v1.11.0
Operating system: Linux, Windows, macOS
**REGRESSION - worked on ODKBriefcasev1.10.1-151gf61342b**

#### Problem description
Forms are not pulled when `Pull before export` option is selected

#### Steps to reproduce the problem
1. The user pulls one form
2. The user exports this form
3. The user fills this form on Collect and sends to Aggregate - make sure that form is visible on Aggregate
4. The user selects `Pull before export` and clicks on `Export` button
![1](https://user-images.githubusercontent.com/3907554/41094109-a60f9cf4-6a3c-11e8-944e-e9ff4c215a39.png)
 5. The new submission was not added to CSV - pull before export does not work

#### Expected behavior
The form is pulled and newest submissions are visible in export file

**Comment by ggalmazor** [comment] 2018-06-07 10:53
Thanks, @mmarciniak90. I can't reproduce the error. I've followed your instructions and this is what I got:

This is the first export. You can see there are no submissions:
![issue_512_before](https://user-images.githubusercontent.com/205913/41095391-8f69bbc8-6a51-11e8-89e6-f217388198f7.png)

Then I sent a submission using Collect.

This is the second export. You can see now there is 1 submission:
![issue_512_after](https://user-images.githubusercontent.com/205913/41095395-915e7d9c-6a51-11e8-9322-1e9a64e1b9dc.png)

I've also checked that the output csv file has the submission I sent

**Comment by ggalmazor** [comment] 2018-06-07 10:55
I've also tried to do the same after closing Briefcase and opening it again, to check that the credentials where being saved. Everything worked as expected:

![issue_512_after_relaunch](https://user-images.githubusercontent.com/205913/41095571-124b9232-6a52-11e8-9327-43dd5eeff159.png)

**Comment by mmarciniak90** [comment] 2018-06-07 12:01
@ggalmazor, I see. I noticed one more problem which can cause this bug!
Steps:
1. The user opens Briefcase and does not select `remember password`
2. The user connects to aggregate and pulls one form
3. The user goes to `Export` tab and chooses `Export directory`
4. The user exports this one form
5. `Pull before export` checkbox is **ACTIVE**
![1](https://user-images.githubusercontent.com/3907554/41098290-5ff1f9e8-6a4a-11e8-8ef1-0cdc8028b3a7.png)

**Closed** 2018-06-07 18:09 UTC
