### ISSUE TITLE
There are active "Details..." buttons without any pulling/pushing activity. 

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#248] opened 2017-11-21 08:45 UTC
#### Software versions 
Briefcase v1.8.0, Java v1.8.0_151, operating system - Ubuntu

#### Problem description
There are active "Details..." buttons without any pulling/pushing activity. 
You are able to display details of pulling/pushing process without executing any processes. Also empty details window appears when you choose one of those buttons.

#### Steps to reproduce the problem
1. Go to pull/push section
2. Choose where Pull data from/Push data to and input url, username and password if necessary. 
3. When forms to pull/push display in table click on one of "Details..." button.

#### Expected behavior
"Details..." button should be active after pulling/pushing some forms and the same with details window which should appear after executing pull/push.

**Comment by kkrawczyk123** [comment] 2018-01-30 11:57
@yanokwa, @lognaturel, @ggalmazor, details buttons are disabled without any activity in export section now, maybe we should disabled them also in pull and push section? If you click on them now, just an empty window displays.

**Comment by icemc** [comment] 2018-01-31 15:14
@opendatakit-bot claim

**Comment by yanokwa** [comment] 2018-02-12 01:30
@icemc I love that you are taking on issues, but you are a bit of a Briefcase veteran so you should leave the quick wins for newer contributors and take on some harder issues!

**Comment by icemc** [comment] 2018-02-12 07:59
Hello @yanokwa great idea. Could you please suggest one you think will be good for me.

**Comment by icemc** [comment] 2018-02-12 07:59
@opendatakit-bot unclaim

**Comment by ggalmazor** [comment] 2018-02-19 15:32
@opendatakit-bot label "contributor friendly"

**Comment by ggalmazor** [comment] 2018-02-19 15:34
This issue should be solved mirroring what's been done in the Export tab. See `FormsTableViewMode.buildDetailButton()` and `FormsTableViewMode.updateDetailButton()`

**Comment by ggalmazor** [comment] 2018-02-21 08:44
@opendatakit-bot claim

**Comment by emajj** [comment] 2018-02-22 06:02
@opendatakit-bot claim

**Comment by ggalmazor** [comment] 2018-02-22 07:30
@opendatakit-bot unclaim

**Comment by emajj** [comment] 2018-02-22 20:07
I was not able to reproduce this. After setting my url to https://opendatakit.appspot.com/ and moved to the pull section, the details buttons are all non active. It's only active during/after pulling.

**Comment by emajj** [comment] 2018-02-22 20:12
![image](https://user-images.githubusercontent.com/36533836/36561779-11d46d40-1815-11e8-821e-344f7a7d5d5f.png)

**Comment by ggalmazor** [comment] 2018-02-23 08:00
Hi @emajj! You're right, we already did this one... :O

@kkrawczyk123, please, close the issue :)

**Closed** 2018-02-23 08:28 UTC
Labels: contributor friendly, in progress
