### ISSUE TITLE
No Suitable driver found for jdbc:hsqldb in (push and pull) using java 1.7.79

### ISSUE THREAD

**Issue by NaderBeshr** [opendatakit/briefcase#203] opened 2017-09-20 23:34 UTC
### Notes :                        in java jre version 1.8 (no issue).

**Comment by batkinson** [comment] 2017-09-22 16:59
Thanks for the report @NaderVIP.

This should be a simple fix and I do see that the installation instructions still list Java 7 https://opendatakit.org/use/briefcase/, despite being end-of-life since around April 2015.

**Comment by NaderVIP** [comment] 2017-09-24 17:56
you don't have to thank me @batkinson
this is the least that i can do for all of you.
in fact you are right it still on the link you added it say briefcase use java 7 and higher.
this is make user confused when they install briefcase with java 7.
feed back will be tough from users.

**Comment by yanokwa** [comment] 2017-09-26 11:44
@batkinson I've filed an issue against the docs at https://github.com/opendatakit/docs/issues/212.

**Comment by rockydcoder** [comment] 2017-10-15 14:12
I want to take this up. I am a bit confused though. What should be the solution? I think updating the docs in the repo has already been handled in [#212](https://github.com/opendatakit/docs/issues/212).

**Comment by lognaturel** [comment] 2017-10-15 21:57
It's good to have the documentation in but until we make a final decision on #158 it would be good to keep supporting Java 7.

I believe it should be straightforward to use the previous version of `hsqldb` when compiling with Java 7. I'm not exactly sure what the process is but it may be as simple as removing the `version` directive. @rockydcoder a great first step would be to try that with both Java 7 and Java 8 and if it works, issue a pull request. If that doesn't work, we should discuss other options here. Thanks! 😊

**Comment by lognaturel** [comment] 2017-10-15 22:08
Oh and if you decide to take it on, please comment with `@opendatakit-bot claim` so the issue is assigned to you!

**Comment by rockydcoder** [comment] 2017-10-16 11:46
@opendatakit-bot claim

**Comment by rockydcoder** [comment] 2017-10-16 11:49
I tried it with `hsqldb - 2.3.5` for both Java 7 and 8 (1.7.0.79 and 1.8.0.101) and it worked fine. Should I raise a PR with that change then?

**Comment by lognaturel** [comment] 2017-10-16 15:46
Ideally the latest version could be used when compiling with Java 8 and `2.3.5` when compiling with Java 7. I believe that's what happens when the `version` is just not explicitly specified. Is that what you confirmed? It would be better not to hardcode a lower version if possible. 

If that works then yes, please issue a PR!

**Comment by rockydcoder** [comment] 2017-10-17 05:51
No, I do not think gradle can resolve dependencies without the version (except for some libraries). Different versions of the same library can be downloaded [see here](https://discuss.gradle.org/t/how-to-get-multiple-versions-of-the-same-library/7400/3), but only one will be picked up at run-time (the latest one). We can force which version to use using [Resolution Strategy](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html), but I do not think that can be done at runtime, according to the jdk used to compile.

**Comment by rockydcoder** [comment] 2017-10-24 02:28
@lognaturel , do you have any thoughts about this? Seems like a low hanging fruit if we just use the `2.3.5` version.

**Comment by lognaturel** [comment] 2017-10-24 03:33
You're absolutely right, solving the problem for developers is not really all that important, it's about people just running the app and what their java versions are. Sorry about that, I didn't stop to think about it long enough. 😣

I see from http://hsqldb.org/doc/changelist_2_0.txt that "version 2.3.5 is released as a separate jar for JRE 1.6 and fully compatible except for the new JDBC features". So yes, using that one sounds good. Please include a quick comment about why the version was picked so we can easily remember!

**Closed** 2017-11-06 19:04 UTC
Labels: bug, contributor friendly, in progress
