### ISSUE TITLE
Media folder doesn't update when pulling twice the same form.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#467] opened 2018-05-18 14:07 UTC
#### Software versions 
Briefcase v1.10.x, Java v1.8.x, operating system Ubuntu, MacOS and Windows

#### Problem description
Media folder doesn't update when pulling twice the same form.

#### Steps to reproduce the problem
1. Run Briefcase, pull a form from aggregate.
2. Attach some media files to the form on the aggregate.
3. Pull the same form once again.
4. Check on that form in your storage directory.

#### Expected behavior
Media should be pulled too, media folder should update.

#### Other information 
I have checked and it worked properly on Briefcase 1.9.
If pull to other storage directory media files are pulled correctly.

**Comment by ggalmazor** [comment] 2018-05-31 09:00
> Attach some media files to the form on the aggregate.

How did you do that? I'm having trouble reproducing the error... Could you give me a step by step guide and maybe the form files you used?

I'm surprised that this fails now because I haven't changed the code that pulls the forms from aggregate (it should do the same thing as before)

**Comment by ggalmazor** [comment] 2018-06-01 18:40
@kkrawczyk123, how do you "attach" a media file to an existing form?

**Comment by lognaturel** [comment] 2018-06-01 22:40
@kkrawczyk123 Did you do it by uploading exactly the same XML but with updated or new media? It's not super discoverable but that's the typical strategy.

**Comment by ggalmazor** [comment] 2018-06-02 05:48
I'll try that!

**Comment by kkrawczyk123** [comment] 2018-06-04 06:19
Yes, I did it exactly that way.

**Comment by ggalmazor** [comment] 2018-06-04 08:45
If I do that I get this error:

![image](https://user-images.githubusercontent.com/205913/40907496-57cd14d6-67e4-11e8-86b3-8b9eeeb4183c.png)

If you're sending the same form, the new media files won't be in the form's manifest and Briefcase can't detect that there are new media files... 

Am I wrong?

**Comment by kkrawczyk123** [comment] 2018-06-05 14:05
I confirm that this issue doesn't occur anymore after merging #474, tested on all 3 systems.

**Comment by ggalmazor** [comment] 2018-06-07 18:33
Then we can close this one, can't we?

**Closed** 2018-06-07 18:34 UTC
