### ISSUE TITLE
Pull/push saving condition improvement. 

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#537] opened 2018-06-19 06:57 UTC
#### Software versions 
Briefcase v1.11.x, Java v1.8.171, operating system: Ubuntu, MacOS and Windows. 

#### Problem description

When credentials are not required from aggregate but set anyway - target is not saved after relaunching briefcase and it can be a little bit confusing as the behavior is exactly the same as for aggregate which requires logging in and target are saved only when Remember password is chosen. So it can be difficult for the user to differentiate those behaviors.

**Comment by kkrawczyk123** [comment] 2018-06-19 06:57
@opendatakit-bot label "needs discussion"

**Comment by ggalmazor** [comment] 2018-06-19 07:46
> When credentials are not required from aggregate but set anyway - target is not saved after relaunching briefcase

That's not the way it works... The source/target is saved only if remember passwords is checked. We changed that in PR #527 to prevent confusing situations.

In the related issue #491, we discussed that the root cause of the problem is that saving a source/target will make Briefcase get the form list on the next launch. Appart from possible defects on Briefcase, this can be a problem when the credentials change on Aggregate, which we can't really control.

I proposed that we could give feedback to the user when we can't load the list of forms on launch. An error dialog with some message like "The saved url and credentials are no longer valid. Please set a pull source again" and give two options: "set source", "clear source".
  - If the user clicks on "set source", open the Remote Server Dialog pre-set with the information we have
  - If the user clicks on "clear source", clear the source and continue launch

I also think that the source selection panel in the pull tab is missing a "reload forms" button.

**Comment by ggalmazor** [comment] 2018-08-30 11:32
Closing in favor of #591 and #620

**Closed by ggalmazor** 2018-08-30 11:32 UTC
Labels: needs discussion
