### ISSUE TITLE
Clear All button is active on Export tab even if list is empty

### ISSUE THREAD

**Issue by mmarciniak90** [opendatakit/briefcase#732] opened 2019-04-12 11:28 UTC
#### Software versions 
Briefcase current master
operating system: Ubuntu 18, Windows 10 (MacOS was not verified)

#### Problem description
`Clear All` button is active on `Export` tab even if list is empty

#### Steps to reproduce the problem
1. User opens Briefcase (first run, cleared prefs)
2. All lists are empty
3. User sees that `Select All` button on Pull/Push tabs is inactive but `Export` tab has active `Clear All` button

![Screenshot from 2019-04-12 13-22-43](https://user-images.githubusercontent.com/3907554/56034118-b21e9580-5d26-11e9-8f01-7bffe9e42694.png)

#### Expected behavior
`Select All` button is inactive

**Comment by ggalmazor** [comment] 2019-04-15 05:49
Thanks, @mmarciniak90! I've been able to reproduce the issue. 

We'll have to fix it an upcoming release to avoid compromising the current code-freeze for v1.5.0, though

**Comment by ggalmazor** [comment] 2019-08-20 09:11
@mayank8318, would you be interested on checking on this one? First we would need to be sure it's still an issue and then close the issue or submit a PR with a fix. What do you say? ;)

**Comment by mayank8318** [comment] 2019-08-20 15:34
@ggalmazor okay on it :)

**Comment by mayank8318** [comment] 2019-08-20 15:34
@opendatakit-bot claim

**Comment by mayank8318** [comment] 2019-08-20 15:38
Yes, the issue is still there:

![Screenshot from 2019-08-20 21-07-15](https://user-images.githubusercontent.com/22395998/63361899-9c814280-c38e-11e9-98f7-bd6ed6e574ba.png)

**Closed** 2019-08-26 07:18 UTC
Labels: bug, in progress
