### ISSUE TITLE
Unable to export forms with punctuation charts in form name

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#800] opened 2019-09-05 11:16 UTC
#### Software versions 
Briefcase v1.17.x, Java v1.x.x, operating system, MacOS, Ubuntu, Windows

#### Problem description
Exporting form with punctuation charts in form name seems to be an infinite process, it freezes export tab. 

#### Steps to reproduce the problem
Export form with punctuation charts in the form name (dots, slashes, probably spaces too)

#### Expected behavior
User should be able to export forms with punctuation charts in form name.

#### Other information 
forms that I have used for testing: 
[punctuation_charts.zip](https://github.com/opendatakit/briefcase/files/3579001/punctuation_charts.zip)

Exception in thread "Thread-21" org.opendatakit.briefcase.reused.BriefcaseException
        at java.util.Optional.orElseThrow(Unknown Source)
        at org.opendatakit.briefcase.ui.export.ExportPanel.lambda$export$10(ExportPanel.java:198)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at org.opendatakit.briefcase.reused.job.JobsRunner.launchAsync(JobsRunner.java:63)
        at org.opendatakit.briefcase.reused.job.JobsRunner.launchAsync(JobsRunner.java:51)
        at org.opendatakit.briefcase.ui.export.ExportPanel.export(ExportPanel.java:229)
        at java.lang.Thread.run(Unknown Source)

**Comment by ggalmazor** [comment] 2019-09-06 08:08
This is a dupe of #799

**Closed by ggalmazor** 2019-09-06 08:08 UTC
