### ISSUE TITLE
Unable to log in to GAE instance on java 9.0.4-openjdk.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#528] opened 2018-06-12 13:32 UTC
#### Software versions 
Briefcase v1.11.x, Java v1.9.0.4-openjdk, operating system: Ubuntu, MacOS 

#### Problem description
Unable to log in to GAE instance on java 9.0.4-openjdk.

#### Steps to reproduce the problem
1. Run briefcase 1.11 on java 9.0.4-openjdk
2. Try to connect to GAE instance

#### Expected behavior
The user should be able to connect GAE instance and use briefcase.

#### Other information 
It is possible to use briefcase with jetty/tomcat aggregate on java 9.0.4-openjdk.

It is possible to run, connect to GAE and use briefcase 1.10 on 9.0.4-openjdk

I am using sdkman to switch java version which can be very important information for further investigation.

**Comment by yanokwa** [comment] 2018-06-13 18:02
@ggalmazor Have you been able to reproduce this?

**Comment by ggalmazor** [comment] 2018-06-13 18:05
Yes. It seems there is some issue with the truststore on that particular version. It's also strange that the old code didn't fail (maybe it was less sensible to "trustore issues").

It would be key to reproduce this with a normal method for installing Java, since @kkrawczyk123 and I use sdkman.io and it could be an issue related to the way it re-packages Java for its installation.

**Comment by ggalmazor** [comment] 2018-06-13 18:07
We used [SSLPoke](https://github.com/MichalHecko/SSLPoke) to test our JVM environment against GAE SSL certificates and we got same results (failure) with Java 9.0.4

**Comment by yanokwa** [comment] 2018-06-13 18:08
Hmm. This looks related to https://forum.opendatakit.org/t/installation-problem-odk-aggregate-ssl-security-error/13510 and https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty/50103533#50103533.

Either way, it sounds like this isn't a blocker on release.

**Comment by ggalmazor** [comment] 2018-06-13 18:08
I agree. There are newer Java9 release that don't have this problem.

**Comment by yanokwa** [comment] 2018-06-14 17:38
Given all that, I don't know if this issue as filed is actionable. I propose @ggalmazor file an issue upstream on sdkman and close this issue.

**Comment by ggalmazor** [comment] 2018-06-18 11:43
I've verified that this issue is not reproducible with a standard Java 9.0.4 installation downloaded from Oracle, confirming that the source of the problem is some kind of mistake during the installation process with SDKMan.

Since is not very probable that our users use SDKMan and the version 9.0.4 is not even available for download, I think we can safely ignore this. I will post an issue on their repo to give them a heads up about this if they don't already know about it.

**Closed** 2018-06-18 19:18 UTC
